name: readme_generator
description: Generates the table for the README for Flutter Community.
version: 1.0.5
maintainer: Jeroen Meijer (@jeroen-meijer)
ignore: true

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  github: 5.0.0
  quiver: ^2.1.2+1
  meta: ^1.1.8
  ansicolor: ^1.0.2
  yaml: ^2.2.0
  crypto: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0+1
