name: readme_generator
description: Generates the table for the README for Flutter Community.
version: 1.0.1
maintainer: Jeroen Meijer (@jeroen-meijer)
ignore: true

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  github: ^4.0.0
  quiver: ^2.0.0+1
  meta: "^1.1.5"
  ansicolor: ^1.0.2
  yaml: "^2.1.14"
  crypto: ^2.0.6